fix: force nng checkout
to prevent build failures like

error: The following untracked working tree files would be overwritten by checkout:
        cmake/FindmbedTLS.cmake

seems to be caused by case sensitivity differences beween file systems (FindmbedTLS.cmake vs FindMbedTLS.cmake)